load("@bazel_skylib//rules:build_test.bzl", "build_test")
load("@npm//:defs.bzl", "npm_link_all_packages")
load("//tools/overpy:overpy.bzl", "overpy_compile")

npm_link_all_packages(name = "node_modules")

overpy_compile(
    name = "gamemode",
    main = "src/main.opy",
    out = "gamemode.txt",
    srcs = glob(["src/**/*.opy"]),
    visibility = ["//visibility:public"],
)

build_test(
    name = "gamemode_build_test",
    targets = [":gamemode"],
)
