name: bazel

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: bazel-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build & Test Gamemode
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Bazel
        uses: bazel-contrib/setup-bazel@0.14.0
        with:
          bazelisk-cache: true
          disk-cache: true
          repository-cache: true

      - name: Build
        run: bazel build //...

      - name: Test
        run: bazel test //...
